### ISSUE TITLE
Documentation missing Arguments

### ISSUE THREAD

**Issue by Z035** [qBraid/qBraid#426] opened 2023-09-29 14:49 UTC
### Environment

- **Python version**:
- **Operating system**:

### What happened?

in # Executing Circuit section
```
>>> qiskit_circuit = circuit0()
>>> cirq_circuit = circuit1()
>>> qjob0 = qdevice.run(qiskit_circuit)
>>> qjob1 = qdevice.run(cirq_circuit)
```
The qjobs are missing arguments ("shots"=50). 

The problem is, when executing without specifying 'shots', the code result in an error:
```
ClientError: An error occurred (400) when calling the CreateQuantumTask operation: Not enough qbraid credits
```
which does not tell you that the real problem is missing shot counts.

### What is the expected outcome?

-

### Any suggestion?

-

**Comment by ryanhill1** [comment] 2023-09-30 19:20
@Z035 Thanks for opening this issue! I tried to recreate the error using the AWS SV1 device

```python
from qbraid import device_wrapper

qdevice = device_wrapper("aws_sv_sim")

qdevice.run(qiskit_circuit)
```

but instead got the following:

```python
ValueError: No result types specified for circuit and shots=0. See `braket.circuits.result_types
```

Which quantum device were you targeting when this happened?

**Comment by Z035** [comment] 2023-09-30 20:09
Im using IronQ's Harmony

**Comment by ryanhill1** [comment] 2023-10-02 15:53
@Z035 Ahh, ok I was able to re-produce! The problem occurred when I tried submitting the task through the qBraid-SDK and through the Amazon Braket SDK directly. So it seems like this bug is caused by the order of error-handling in the qBraid Quantum Jobs API.

I will open the necessary issue in the private qBraid API repository and close this issue when it is resolved. Thanks!

**Comment by Z035** [comment] 2023-10-02 16:36
😆

**Closed** 2024-05-15 13:01 UTC
Labels: bug 🐛, qbraid-lab 🔬
